server:
  port : 8089

spring:
   kafka:
     producer:
        bootstrap-servers: localhost:9092
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: rafael.alcocer.caldera.serializer.CustomSerializer
        topic-name: generic-topic
